# Install script for directory: /home/aaron/cellmate/opencv/modules

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/androidcamera/.androidcamera/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/calib3d/.calib3d/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/contrib/.contrib/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/core/.core/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cuda/.cuda/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudaarithm/.cudaarithm/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudabgsegm/.cudabgsegm/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudacodec/.cudacodec/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudafeatures2d/.cudafeatures2d/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudafilters/.cudafilters/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudaimgproc/.cudaimgproc/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudalegacy/.cudalegacy/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudaoptflow/.cudaoptflow/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudastereo/.cudastereo/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudawarping/.cudawarping/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudev/.cudev/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/features2d/.features2d/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/flann/.flann/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/highgui/.highgui/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/imgproc/.imgproc/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/java/.java/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/legacy/.legacy/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/matlab/.matlab/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/ml/.ml/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/nonfree/.nonfree/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/objdetect/.objdetect/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/optim/.optim/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/photo/.photo/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/python/.python/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/shape/.shape/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/softcascade/.softcascade/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/stitching/.stitching/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/superres/.superres/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/ts/.ts/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/video/.video/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/videostab/.videostab/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/viz/.viz/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/world/.world/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/core/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/flann/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/imgproc/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/highgui/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/features2d/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/calib3d/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudaarithm/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/ml/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/nonfree/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/objdetect/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/video/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/contrib/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudawarping/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cuda/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudafilters/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudaimgproc/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/legacy/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudabgsegm/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudacodec/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudafeatures2d/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudaoptflow/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/cudastereo/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/optim/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/photo/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/softcascade/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/python/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/shape/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/stitching/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/superres/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/ts/cmake_install.cmake")
  INCLUDE("/home/aaron/cellmate/ocv_binaries/modules/videostab/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

